### PR TITLE
setup project structure

### PR DESCRIPTION
**Pull request by Gschrooyen**
setup a gradle project with 1 Helloworld class and 1 test class

### CODE REVIEW

**Comment by timpeeters** [comment]
For Gradle only the following files should be in version control:

gradlew.bat
gradlew
gradle/wrapper/gradle-wrapper.jar
gradle/wrapper/gradle-wrapper.properties

The .gradle directory is specific per user/build and should therefor not be in version control.

**Comment by timpeeters** [comment]
IDE specific configuration files should not be in version control: .idea

**Comment by timpeeters** [comment]
Please update to Gradle version 6.3. Currently the wrapper is a bit outdated (4.8).
https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

**Comment by timpeeters** [comment]
Almost there I believe. I would however recommend some small fixes to the .gitignore file:

The following should be sufficient to ignore all Intellij project files:
.idea
*.iml
*.iws

The following should be sufficent to ignore all unnecessary Gradle file:
.gradle
build/


All other pattern matches like .idea/**/... are already included in the list above and can be removed imho.
At the bottom there are some inverted matches:
!gradlew.bat
!gradlew
!gradle/wrapper/gradle-wrapper.jar
!gradle/wrapper/gradle-wrapper.properties
These can all be removed I guess.

**Comment by Gschrooyen** [comment]
i've also excluded the build .jar files so that is why i need the inverted match for:
!gradle/wrapper/gradle-wrapper.jar

**Pull request merged**
